# Generated by Django 4.2.4 on 2023-08-31 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tagger', '0001_initial'),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmessagesmodel',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.chatsmodel'),
        ),
        migrations.AddField(
            model_name='usersmessagesmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.usersmodel'),
        ),
    ]
