"""
Django settings for django_telegram_tagger project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+i&pq@#7+w=up*2c@45j^-7!om)dbs$9fij5f=8^4_0eqhi4l0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

DOMAIN_NAME = os.environ.get('DOMAIN', '')

ALLOWED_HOSTS = [
    '*'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'home',
    'authentication',
    'tagger',

    'telegram',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_telegram_tagger.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_telegram_tagger.wsgi.application'

LOGOUT_REDIRECT_URL = reverse_lazy('login-page')
LOGIN_URL = reverse_lazy('login-page')

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db' / 'db.sqlite3',
    }
}

SESSION_COOKIE_AGE = 60 * 60 * 24

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []
AUTH_USER_MODEL = 'telegram.CustomUserModel'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = '/static/'
STATIC_URL = 'static-files/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Telegram Settings
DEFAULT_SETTINGS = {
    'theme': 'dark',

    'admins_list': '',

    'set_username_message': '**Username is set!**',
    'set_username_error_message': '**The number of character is too many!**',
    'set_password_message': '**Password is set!**',
    'set_password_set_username_first_error_message': '**First please using command\n'
                                                     '`/setusername`\n'
                                                     'set username!**',
    'set_password_invalid_error_message': '**The number of characters is too many!**',
    'settings_message': '[Click for entering settings panel!]({})',
    'help_message': '`{}`\n**{}**',

    'set_username_command': '/setusername',
    'set_password_command': '/setpassword',
    'settings_command': '/settings',
    'help_command': '/help',
}

TELEGRAM_SESSION = 'app'
TELEGRAM_API_ID = 3195701
TELEGRAM_API_HASH = '5f90aac24b411f83faa5f57e18274430'
